### ISSUE TITLE
A few issues

### ISSUE THREAD

**Issue by bohdantrotsenko** [jposada202020/CircuitPython_BMI160#1]
Hi.
I've tried your code with my BMI160 from DRRobot, using circuit python 9 and raspberry pico.

I had to do a little patch
```
import busio
SDA, SCL = board.GP16, board.GP17
i2c = busio.I2C(SCL, SDA)
#i2c = board.I2C()  # uses board.SCL and board.SDA
```
To make the code work.

The code crashed around line 411 (out of index exception) but I fixed that.

Running the code it felt like the sensor is frozen.
I then started fidgeting the sensor with my nail, eventually it came to life and started sending data.
So, maybe it needs some kind of changing mode before streaming data.

Also the output was not in `m/s^2`, but some kind of "relative", where 1.0 means `g`.

Thanks.

**Comment by jposada202020** [comment]
Hello I do have the same sensor, normally I prefer to test with the borad.sda, board.scl deafult definitions as it is easier. However, I could not reproduce the error. I have changed the units according to your comments in the new release. Thanks.
